<?php

/**
 * General Configuration
 *
 * All of your system's general configuration settings go in here. You can see a
 * list of the available settings in vendor/craftcms/cms/src/config/GeneralConfig.php.
 *
 * @see \craft\config\GeneralConfig
 */

use craft\helpers\App;

$isDev = App::env('ENVIRONMENT') === 'dev';
$isProd = App::env('ENVIRONMENT') === 'production';

return [
    '*' => [
        'defaultWeekStartDay'  => 1, // Default Week Start Day (0 = Sunday, 1 = Monday...)
        'omitScriptNameInUrls' => true, // Whether generated URLs should omit "index.php"
        'cpTrigger'            => App::env('CP_TRIGGER') ?: 'admin', // The URI segment that tells Craft to load the control panel
        'securityKey'          => App::env('SECURITY_KEY'), // The secure key Craft will use for hashing and encrypting data
        'devMode'              => $isDev, // Whether Dev Mode should be enabled (see https://craftcms.com/guides/what-dev-mode-does)
        'allowAdminChanges'    => $isDev, // Whether administrative changes should be allowed
        'disallowRobots'       => !$isProd, // Whether crawlers should be allowed to index pages and following links
        'defaultDirMode'       => 0775,
        'defaultFileMode'      => 0775,
        'handleCasing'         => 'snake', // The casing to use for autogenerated component handles.
        'indexTemplateFilenames' => ['index', 'main'],
        'privateTemplateTrigger' => null,
        'cpTrigger' => 'cp',
    ],
    'dev' => [
        'devMode'              => true,
        'allowAdminChanges'    => true, // Set this to `false` to prevent administrative changes from being made
        'allowUpdates'         => true, // Don’t allow updates
        'disallowRobots'       => true, // Prevent crawlers from indexing pages and following links
    ],
];
