<?php

/**
 * General Configuration
 *
 * All of your system's general configuration settings go in here. You can see a
 * list of the available settings in vendor/craftcms/cms/src/config/GeneralConfig.php.
 *
 * @see \craft\config\GeneralConfig
 */

use craft\helpers\App;

$isLocal = App::env('ENVIRONMENT') === 'local';
$isDev   = App::env('ENVIRONMENT') === 'dev';
$isProd  = App::env('ENVIRONMENT') === 'prod';

return [

    '*' => [

        // Default Week Start Day (0 = Sunday, 1 = Monday...)
        'defaultWeekStartDay'    => 1,

        // Whether generated URLs should omit "index.php"
        'omitScriptNameInUrls'   => true,

        // The URI segment that tells Craft to load the control panel
        'cpTrigger'              => 'cp',

        // The secure key Craft will use for hashing and encrypting data
        'securityKey'            => App::env('SECURITY_KEY'),

        // Whether Dev Mode should be enabled (see https://craftcms.com/guides/what-dev-mode-does)
        'devMode'                => $isDev,

        // Whether administrative changes should be allowed.
        'allowAdminChanges'      => $isDev,

        // Whether Craft should allow system and plugin updates in the control panel, and plugin installation from the Plugin Store.
        'allowUpdates'           => $isDev,

        // Whether crawlers should be allowed to index pages and following links.
        'disallowRobots'         => !$isProd,

        // The default permission to be set for newly-generated directories.
        'defaultDirMode'         => 0774,

        // The default permission to be set for newly-generated files.
        'defaultFileMode'        => 0774,

        // The casing to use for autogenerated component handles.
        'handleCasing'           => 'snake',

        // The template filenames Craft will look for within a directory.
        'indexTemplateFilenames' => ['index'],

        // The template path segment prefix that should be used to identify “private” templates.
        'privateTemplateTrigger' => null,

    ],

    'local' => [],

    'dev' => [],

    'stage' => [],

    'prod' => [],

];
