baseUrl: '@web/fr'
enabled: true
handle: craftTemplate_fr
hasUrls: true
language: fr
name: 'Craft Template FR'
primary: false
siteGroup: 62832241-339f-4b80-84d1-f6f69e2ed403 # Craft Template
sortOrder: 3
