baseUrl: '@web/en'
enabled: true
handle: craftTemplate_en
hasUrls: true
language: en
name: 'Craft Template EN'
primary: false
siteGroup: 62832241-339f-4b80-84d1-f6f69e2ed403 # Craft Template
sortOrder: 2
